// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {tools} from '../models';
import {main} from '../models';
import {engine} from '../models';

export function AIAnalyze(arg1:string):Promise<string>;

export function AITranscribe(arg1:string):Promise<void>;

export function AITranslateSubs(arg1:string):Promise<void>;

export function AddAssets(arg1:Array<string>):Promise<Array<project.Asset>>;

export function AddAudioClip(arg1:string,arg2:number):Promise<project.AudioClip>;

export function AddClip(arg1:string,arg2:number):Promise<project.Clip>;

export function AddMediaOverlay(arg1:string,arg2:number,arg3:number):Promise<project.Overlay>;

export function AddOverlay(arg1:string,arg2:number,arg3:number):Promise<project.Overlay>;

export function ApplySilenceCut(arg1:string,arg2:Array<tools.Silence>):Promise<number>;

export function BuildFromScript(arg1:string):Promise<number>;

export function CancelExport():Promise<void>;

export function CancelPreview():Promise<void>;

export function CheckUpdate():Promise<tools.UpdateInfo>;

export function ChooseExportPath(arg1:string):Promise<string>;

export function ChooseLUTFile():Promise<string>;

export function ClearSubtitles():Promise<void>;

export function ColorMatch(arg1:string,arg2:string):Promise<project.Clip>;

export function CurrentJob():Promise<string>;

export function DetachAudio(arg1:string):Promise<project.Asset>;

export function DetectAssetScenes(arg1:string,arg2:number):Promise<Array<tools.SceneMark>>;

export function DetectClipSilence(arg1:string,arg2:number,arg3:number):Promise<Array<tools.Silence>>;

export function DuplicateAudioClip(arg1:string):Promise<project.AudioClip>;

export function DuplicateClip(arg1:string):Promise<project.Clip>;

export function ExportSRTDialog():Promise<string>;

export function FastCut(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GenerateProxies():Promise<void>;

export function GetAISettings():Promise<main.AISettingsResponse>;

export function GetAssetSourceURL(arg1:string):Promise<string>;

export function GetAssetThumb(arg1:string,arg2:number):Promise<string>;

export function GetClipFrameURL(arg1:string,arg2:number):Promise<string>;

export function GetDiagnostics():Promise<main.DiagnosticsResponse>;

export function GetProxyURL(arg1:string):Promise<string>;

export function GetState():Promise<main.StateResponse>;

export function GetUseProxy():Promise<boolean>;

export function GetVersion():Promise<string>;

export function ImportMediaDialog():Promise<Array<project.Asset>>;

export function ImportSRTDialog():Promise<project.SubtitlesTrack>;

export function ListTTSVoices():Promise<Array<tools.VoiceInfo>>;

export function ListTransitions():Promise<Array<main.TransInfo>>;

export function MoveClip(arg1:string,arg2:number):Promise<void>;

export function NewProject(arg1:boolean):Promise<void>;

export function OpenInFolder(arg1:string):Promise<void>;

export function OpenProjectDialog():Promise<project.Document>;

export function QuickConcat(arg1:Array<string>,arg2:string):Promise<string>;

export function RemoveAsset(arg1:string):Promise<void>;

export function RemoveAudioClip(arg1:string):Promise<void>;

export function RemoveClip(arg1:string):Promise<void>;

export function RemoveOverlay(arg1:string):Promise<void>;

export function RenderPreview():Promise<void>;

export function RunQCAsset(arg1:string):Promise<tools.QCReport>;

export function RunQCCurrent():Promise<tools.QCReport>;

export function RunSelfTest():Promise<void>;

export function SaveFramePNG(arg1:string,arg2:number):Promise<string>;

export function SaveProject():Promise<string>;

export function SaveProjectAs():Promise<string>;

export function SetAISettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetCanvas(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetCredits(arg1:Array<string>,arg2:number,arg3:number):Promise<void>;

export function SetDocFlags(arg1:boolean,arg2:boolean):Promise<void>;

export function SetDocument(arg1:project.Document):Promise<void>;

export function SetGitHubRepo(arg1:string):Promise<void>;

export function SetSubtitleStyle(arg1:boolean,arg2:number,arg3:string):Promise<void>;

export function SetTimecode(arg1:boolean,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function SetTransition(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetUseProxy(arg1:boolean):Promise<void>;

export function SetWatermark(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function SplitClip(arg1:string,arg2:number):Promise<project.Clip>;

export function StartExport(arg1:engine.ExportRequest):Promise<void>;

export function TTSGenerate(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<string>;

export function UpdateAudioClip(arg1:string,arg2:main.AudioClipPatch):Promise<project.AudioClip>;

export function UpdateClip(arg1:string,arg2:main.ClipPatch):Promise<project.Clip>;

export function UpdateOverlay(arg1:string,arg2:main.OverlayPatch):Promise<project.Overlay>;
