// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIAnalyze(arg1) {
  return window['go']['main']['App']['AIAnalyze'](arg1);
}

export function AITranscribe(arg1) {
  return window['go']['main']['App']['AITranscribe'](arg1);
}

export function AITranslateSubs(arg1) {
  return window['go']['main']['App']['AITranslateSubs'](arg1);
}

export function AddAssets(arg1) {
  return window['go']['main']['App']['AddAssets'](arg1);
}

export function AddAudioClip(arg1, arg2) {
  return window['go']['main']['App']['AddAudioClip'](arg1, arg2);
}

export function AddClip(arg1, arg2) {
  return window['go']['main']['App']['AddClip'](arg1, arg2);
}

export function AddMediaOverlay(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMediaOverlay'](arg1, arg2, arg3);
}

export function AddOverlay(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddOverlay'](arg1, arg2, arg3);
}

export function ApplySilenceCut(arg1, arg2) {
  return window['go']['main']['App']['ApplySilenceCut'](arg1, arg2);
}

export function BuildFromScript(arg1) {
  return window['go']['main']['App']['BuildFromScript'](arg1);
}

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function CancelPreview() {
  return window['go']['main']['App']['CancelPreview']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ChooseExportPath(arg1) {
  return window['go']['main']['App']['ChooseExportPath'](arg1);
}

export function ChooseLUTFile() {
  return window['go']['main']['App']['ChooseLUTFile']();
}

export function ClearSubtitles() {
  return window['go']['main']['App']['ClearSubtitles']();
}

export function ColorMatch(arg1, arg2) {
  return window['go']['main']['App']['ColorMatch'](arg1, arg2);
}

export function CurrentJob() {
  return window['go']['main']['App']['CurrentJob']();
}

export function DetachAudio(arg1) {
  return window['go']['main']['App']['DetachAudio'](arg1);
}

export function DetectAssetScenes(arg1, arg2) {
  return window['go']['main']['App']['DetectAssetScenes'](arg1, arg2);
}

export function DetectClipSilence(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetectClipSilence'](arg1, arg2, arg3);
}

export function DuplicateAudioClip(arg1) {
  return window['go']['main']['App']['DuplicateAudioClip'](arg1);
}

export function DuplicateClip(arg1) {
  return window['go']['main']['App']['DuplicateClip'](arg1);
}

export function ExportSRTDialog() {
  return window['go']['main']['App']['ExportSRTDialog']();
}

export function FastCut(arg1, arg2, arg3) {
  return window['go']['main']['App']['FastCut'](arg1, arg2, arg3);
}

export function GenerateProxies() {
  return window['go']['main']['App']['GenerateProxies']();
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetAssetSourceURL(arg1) {
  return window['go']['main']['App']['GetAssetSourceURL'](arg1);
}

export function GetAssetThumb(arg1, arg2) {
  return window['go']['main']['App']['GetAssetThumb'](arg1, arg2);
}

export function GetClipFrameURL(arg1, arg2) {
  return window['go']['main']['App']['GetClipFrameURL'](arg1, arg2);
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetProxyURL(arg1) {
  return window['go']['main']['App']['GetProxyURL'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetUseProxy() {
  return window['go']['main']['App']['GetUseProxy']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportMediaDialog() {
  return window['go']['main']['App']['ImportMediaDialog']();
}

export function ImportSRTDialog() {
  return window['go']['main']['App']['ImportSRTDialog']();
}

export function ListTTSVoices() {
  return window['go']['main']['App']['ListTTSVoices']();
}

export function ListTransitions() {
  return window['go']['main']['App']['ListTransitions']();
}

export function MoveClip(arg1, arg2) {
  return window['go']['main']['App']['MoveClip'](arg1, arg2);
}

export function NewProject(arg1) {
  return window['go']['main']['App']['NewProject'](arg1);
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function QuickConcat(arg1, arg2) {
  return window['go']['main']['App']['QuickConcat'](arg1, arg2);
}

export function RemoveAsset(arg1) {
  return window['go']['main']['App']['RemoveAsset'](arg1);
}

export function RemoveAudioClip(arg1) {
  return window['go']['main']['App']['RemoveAudioClip'](arg1);
}

export function RemoveClip(arg1) {
  return window['go']['main']['App']['RemoveClip'](arg1);
}

export function RemoveOverlay(arg1) {
  return window['go']['main']['App']['RemoveOverlay'](arg1);
}

export function RenderPreview() {
  return window['go']['main']['App']['RenderPreview']();
}

export function RunQCAsset(arg1) {
  return window['go']['main']['App']['RunQCAsset'](arg1);
}

export function RunQCCurrent() {
  return window['go']['main']['App']['RunQCCurrent']();
}

export function RunSelfTest() {
  return window['go']['main']['App']['RunSelfTest']();
}

export function SaveFramePNG(arg1, arg2) {
  return window['go']['main']['App']['SaveFramePNG'](arg1, arg2);
}

export function SaveProject() {
  return window['go']['main']['App']['SaveProject']();
}

export function SaveProjectAs() {
  return window['go']['main']['App']['SaveProjectAs']();
}

export function SetAISettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAISettings'](arg1, arg2, arg3, arg4);
}

export function SetCanvas(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetCanvas'](arg1, arg2, arg3, arg4);
}

export function SetCredits(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCredits'](arg1, arg2, arg3);
}

export function SetDocFlags(arg1, arg2) {
  return window['go']['main']['App']['SetDocFlags'](arg1, arg2);
}

export function SetDocument(arg1) {
  return window['go']['main']['App']['SetDocument'](arg1);
}

export function SetGitHubRepo(arg1) {
  return window['go']['main']['App']['SetGitHubRepo'](arg1);
}

export function SetSubtitleStyle(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSubtitleStyle'](arg1, arg2, arg3);
}

export function SetTimecode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetTimecode'](arg1, arg2, arg3, arg4, arg5);
}

export function SetTransition(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTransition'](arg1, arg2, arg3);
}

export function SetUseProxy(arg1) {
  return window['go']['main']['App']['SetUseProxy'](arg1);
}

export function SetWatermark(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetWatermark'](arg1, arg2, arg3, arg4, arg5);
}

export function SplitClip(arg1, arg2) {
  return window['go']['main']['App']['SplitClip'](arg1, arg2);
}

export function StartExport(arg1) {
  return window['go']['main']['App']['StartExport'](arg1);
}

export function TTSGenerate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TTSGenerate'](arg1, arg2, arg3, arg4);
}

export function UpdateAudioClip(arg1, arg2) {
  return window['go']['main']['App']['UpdateAudioClip'](arg1, arg2);
}

export function UpdateClip(arg1, arg2) {
  return window['go']['main']['App']['UpdateClip'](arg1, arg2);
}

export function UpdateOverlay(arg1, arg2) {
  return window['go']['main']['App']['UpdateOverlay'](arg1, arg2);
}
